### PR TITLE
fixes issue 10: mapBoth vs elim

### PR DESCRIPTION
**Pull request by toastal**
fixes issue #10 where the name is misleading

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
See comment https://github.com/elm-community/result-extra/issues/10#issuecomment-248203746.

**Comment by jvoigtlaender** [comment]
For the record, I'd support (and merge, in the apparent absence of the maintainer of this repository) this if `elim` were renamed to `mapFromBoth`.

**Comment by toastal** [comment]
PR for #10

**Comment by twopoint718** [comment]
As the one who introduced the `mapBoth` name, I absolutely agree. This is much clearer and more consistent. Thanks!

**Comment by toastal** [comment]
When does this get published?

**Comment by jvoigtlaender** [comment]
I can publish it within the next hour.

**Comment by jvoigtlaender** [comment]
It's published.

**Pull request merged**
